apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: vm-operator-account-binding
subjects:
- kind: ServiceAccount
  name: vm-operator # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: vm-operator-account
  apiGroup: rbac.authorization.k8s.io
