# A demo CRD for the Kopf example operators.
# Use it with Kubernetes 1.15 and below.
# For Kubernetes 1.16 and above, use crd.yaml.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubeclusters.cloud.org
spec:
  scope: Namespaced
  group: cloud.org
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: KubeCluster
    plural: kubeclusters
    singular: kubecluster
    shortNames:
      - kubecls
      - kcls
      - kc
  additionalPrinterColumns:
    - name: Version
      type: string
      priority: 0
      JSONPath: .spec.version
      description: Kubernetes cluster version
    - name: Worker
      type: string
      priority: 0
      JSONPath: .status.worker
      description: Number of kubernetes workers
    - name: Description
      type: string
      priority: 0
      JSONPath: .status.description
      description: Cluster description.
